### ISSUE TITLE
Informative report

### ISSUE THREAD

**Issue by martijnrusschen** [martijnrusschen/gh-integration#1]
**Link**:		https://enorekcah.com/reports/157883  
**Date**:		2017-11-15 18:24:01 UTC  
**By**:		miray  
**Weakness**:	Cross-site Scripting (XSS) - DOM  
  
**Details**:  
Hi all,

This is an informative report good luck

**Comment by martijnrusschen** [comment]
Wow, it works!

**Comment by saida** [comment]
saida99 reopened the report on HackerOne:<br /><br />
