### ISSUE TITLE
asdas

### ISSUE THREAD

**Issue by stacyspiva** [martijnrusschen/gh-integration#7]
Link:		https://hackerone.com/reports/1117862  
Date:		2021-03-05 09:26:41 UTC  
By:		martijn  
Weakness:	SQL Injection  
  
Details:  
## Summary:
[add summary of the vulnerability]

## Steps To Reproduce:
[add details for how we can reproduce the issue]

  1. [add step]
  1. [add step]
  1. [add step]

## Supporting Material/References:
[list any additional material (e.g. screenshots, logs, etc.)]

  * [attachment / reference]

## Impact

sadas

**Comment by kiroxan** [comment]
kiroxan posted a comment on HackerOne:

public comment
