### ISSUE TITLE
sadas

### ISSUE THREAD

**Issue by stacyspiva** [martijnrusschen/gh-integration#8]
Link:		https://hackerone.com/reports/1127321  
Date:		2021-03-16 17:46:11 UTC  
By:		martijn  
Weakness:	Array Index Underflow  
  
Details:  
## Steps To Reproduce:
[add details for how we can reproduce the issue]

  1. [add step]
  1. [add step]
  1. [add step]

## Supporting Material/References:
[list any additional material (e.g. screenshots, logs, etc.)]

  * [attachment / reference]

## Impact

asdas

**Comment by martijnrusschen** [comment]
tadsd
